import { SVGProps } from "react";

export type IconSvgProps = SVGProps<SVGSVGElement> & {
  size?: number;
};

 export interface IUserRegistration {
  name: string;
  email: string;
  password: string;
  profileImage?: string;
  phone: string;
  address?: string;
  role: string;
}

export interface IUser {
  [x: string]: any;
  _id: string;
  name: string;
  role: string;
  email: string;
  address:string;
  isPremium: boolean;
  verified: boolean;
  phone?: string;
  followers?: number;
  following?: number;
  profileImage?: string;
 
}



export interface IPost {
  _id?: string; // Optional because it will be generated by MongoDB
  title: string;
  content: string; // Rich text content or Markdown
  image: {
    type: [string], // Array of strings
    default: [],
  },
  userId: string; // ID of the user who created the post
  category: string; // E.g., Vegetables, Flowers, etc.
  isPremium: boolean; // Indicates if the post is premium
  upvotes?: number; // Number of upvotes
  downvotes?: number; // Number of downvotes
  comments?: string[]; // Array of comment IDs
  createdAt?: Date; // Optional, will be set by MongoDB
  updatedAt?: Date; // Optional, will be set by MongoDB
}
